# reward settings
name: bohn_orig
weights: # bohn code | bohn paper | / max_error | unit
    roll:
        scaling: 3.3 # 3.2 | 3.3 | 1.047198 | 1.0
        clip_max: 0.4
    pitch:
        scaling: 2.25 # 3.2 | 2.25 | 0.698132 | 1.0
        clip_max: 0.4
    act_var:
        enabled: true
        scaling: 60
        clip_max: 0.2