# parent class JSBSimEnv config
fdm_freq: 100.0 # 120 Hz being the default JSBSim freq
agent_freq: 100.0
episode_length_s: 20.0
viz_time_factor: 50.0
debug: False
render_mode: "none"

# JSBSim simulation env options - train
train_sim_options:
    seed: ???
    atmosphere:
        severity: null
        variable: True
        wind:
            enable: True
            rand_continuous: True
        turb:
            enable: True
        gust:
            enable: True
    rand_fdm:
        enable: False

# JSBSim simulation env options - eval
eval_sim_options:
    seed: 10
    atmosphere:
        severity: "all"
        variable: False
        wind:
            enable: True
            rand_continuous: False
        turb:
            enable: True
        gust:
            enable: True
    rand_fdm:
        enable: False