# parent class JSBSimEnv config
fdm_freq: 100.0 # 120 Hz being the default JSBSim freq
agent_freq: 100.0
episode_length_s: 20.0
viz_time_factor: 50.0
debug: True
render_mode: "none"

# settings for env with light constant wind and all turbulence levels
# JSBSim simulation env options - train
train_sim_options:
    seed: ???
    atmosphere:
        severity: null
        variable: True
        wind:
            enable: True
            wind_severity: light
            rand_continuous: False
        turb:
            enable: True
        gust:
            enable: False
    rand_fdm:
        enable: False

# JSBSim simulation env options - eval
eval_sim_options:
    seed: ???
    atmosphere:
        severity: all
        variable: False
        wind:
            enable: True
            wind_severity: light
            rand_continuous: False
        turb:
            enable: True
        gust:
            enable: False
    rand_fdm:
        enable: False