# config for PPO training of Attitude Control Task as done in the Bohn et al. paper

# parent class JSBSimEnv config
JSBSimEnv:
    fdm_freq: 240.0 # 120 Hz being the default JSBSim freq
    agent_freq: 60.0
    episode_length_s: 20.0
    viz_time_factor: 1.0

# task specific child class config: AttitudeControlTaskEnv
AttitudeControlTaskEnv:
    flight_data_logfile: "data/gym_flight_data.csv"
    obs_is_matrix: True
    obs_history_size: 5

    error_success_tholds: # error thresholds for success
        Va: 0.1 # m/s
        pitch: 0.1 # rad
        roll: 0.1 # rad

    success_time_s: 5.0

    reward_weights:
        Va:
            scaling: 3.3
            clip_min: 0.0
            clip_max: 0.3
        roll:
            scaling: 3.3
            clip_min: 0.0
            clip_max: 0.3
        pitch:
            scaling: 2.25
            clip_min: 0.0
            clip_max: 0.3
        act_var: # action variation
            scaling: 60.0
            clip_min: 0.0
            clip_max: 0.1
