defaults:
    - rl: ppo
    - env/jsbsim: noatmo
    - env/task/mdp: my_bohn
    - env/task/reward: my_bohn

# eval
model_path: null # path to a pretrained model for eval
ref_file: simple_easy.npy # path to a reference file for eval
res_file: test.csv # path to a results file for eval