defaults:
    - rl: ppo
    - env/jsbsim: noatmo
    - env/task/mdp: my_bohn
    - env/task/reward: my_bohn

# eval
model_path: null # path to a pretrained model for eval
ref_file: simple_easy # path to a reference file for eval
res_file: test # path to a results file for eval


# to be changed, env_id should be out of the agents (PID/RL) dict
PID:
    env_id: ACBohnNoVaIErr-v0
