# config for PPO training of Attitude Control Task without airspeed control

# parent class JSBSimEnv config
JSBSimEnv:
    fdm_freq: 100.0 # 120 Hz being the default JSBSim freq
    agent_freq: 100.0
    episode_length_s: 20.0
    viz_time_factor: 50.0

# task specific child class config: AttitudeControlTask
AttitudeControlTask:
    obs_is_matrix: True
    obs_history_size: 15 # default 5
    act_history_size: 15

    reward_weights: # bohn code | bohn paper | / max_error | unit
        roll:
            scaling: 3.3 # 3.2 | 3.3 | 1.047198 | 1.0
            clip_min: 0.0
            clip_max: 0.5
        pitch:
            scaling: 2.25 # 3.2 | 2.25 | 0.698132 | 1.0
            clip_min: 0.0
            clip_max: 0.5