# config for PPO training of Attitude Control Task without airspeed control

# parent class JSBSimEnv config
JSBSimEnv:
    fdm_freq: 100.0 # 120 Hz being the default JSBSim freq
    agent_freq: 100.0
    episode_length_s: 20.0
    viz_time_factor: 5.0

# task specific child class config: AttitudeControlTask
AttitudeControlTask:
    obs_is_matrix: True
    obs_history_size: 5
    act_history_size: 5

    reward_weights:
        roll:
            scaling: 3.2
            clip_min: 0.0
            clip_max: 0.5
        pitch:
            scaling: 3.2
            clip_min: 0.0
            clip_max: 0.5