# config for PPO training of Attitude Control Task inspired from Bohn et al. PPO paper
# and the CAPS paper (cited in htie follow up paper)

# parent class JSBSimEnv config
JSBSimEnv:
    fdm_freq: 100.0 # 120 Hz being the default JSBSim freq
    agent_freq: 100.0
    episode_length_s: 20.0
    viz_time_factor: 50.0

# task specific child class config: AttitudeControlTask
AttitudeControlTask:
    obs_is_matrix: True
    obs_history_size: 5
    act_history_size: 5

    reward_weights:
        roll:
            scaling: 3.2
            clip_min: 0.0
            clip_max: 0.333
        pitch:
            scaling: 3.2
            clip_min: 0.0
            clip_max: 0.333
        Va:
            scaling: 25.0
            clip_min: 0.0
            clip_max: 0.333

        # those weights are not used in the final reward computation
        # only for logging in the plots to give a metric on action smoothness
        act_var: # action variation
            scaling: 60.0
            clip_min: 0.0
            # clip_max: 0.1
        act_bounds:
            scaling: 1.0