defaults:
    - _self_
    - rl: ppo
    - env/jsbsim: noatmo
    - env/task/mdp: no_hist_all
    - env/task/reward: my_bohn

# training
# reference attitude angle limits (+/- degrees)
roll_limit: 60 # 45 up to moderate, 60 up to hard
pitch_limit: 30 # 25 up to moderate, 30 up to hard

# eval
model_path: null # path to a pretrained model for eval
ref_file: simple_easy # path to a reference file for eval
res_file: test # path to a results file for eval


# to be changed, env_id should be out of the agents (PID/RL) dict
PID:
    env_id: ACBohnNoVaIErr-v0
